# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  extra_joints:
    - name: 'sam_auv/pose_sensor_joint'
      position: 0.0
    - name: 'sam_auv_sonarleft_joint'
      position: 0.0
    - name: 'sam_auv_sonarright_joint'
      position: 0.0
    - name: 'sam_auv/cover_joint'
      position: 0.0
    - name: 'sam_auv/camera_joint'
      position: 0.0
    - name: 'sam_auv/camera_thruster_joint'
      position: 0.0
    - name: 'sam_auv/camera_optical_joint'
      position: 0.0
    - name: 'sam_auv/camera_thruster_optical_joint'
      position: 0.0
    - name: 'sam_auv/imu_joint'
      position: 0.0

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: sam_auv/shaft_joint1
  pid: {p: 100.0, i: 0.1, d: 10.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: sam_auv/shaft_joint2
  pid: {p: 100.0, i: 0.1, d: 10.0}
